default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: snusavij
  password: 6310
  host: localhost

development:
  <<: *default
  database: erpcore_development

test:
  <<: *default
  database: erpcore_test

production:
  adapter: postgresql
  encoding: unicode
  database: erpcore
  username: snusavij
  password: 6310
  host: localhost
  pool: 5